env:
  browser: true
  es6: true
extends:
  - airbnb-base
  - eslint:recommended
  - p5js
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
